services:
  - name: flask-app
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    envVars:
      - key: GROQ_API_KEY
        sync: false  # Set this manually in Render Dashboard
